-- CREATE DATABASE IF NOT EXISTS ${MARIADB_DATABASE};
--CREATE DATABASE IF NOT EXISTS development_db;

-- CREATE DATABASE IF NOT EXISTS ${MARIADB_TEST_DB};
CREATE DATABASE IF NOT EXISTS test_db;

-- GRANT ALL PRIVILEGAES ON '${MARIADB_TEST_DB}'.* TO '${DB_USERNAME}'@localhost;
GRANT ALL PRIVILEGAES ON 'text_db'.* TO 'developer'@localhost;