services:
  #nginx:
  #  image: nginx

  #postgres:
  #  image: postgres:16.3-alpine
  #  container_name: postgres
  #  restart: unless-stopped
  #  tty: true
  #  ports:
  #    - ${DB_PORT_OUT}:${DB_PORT}
  #  volumes:
  #    - db_data:/var/lib/postgresql/data
  #  environment:
  #    POSTGRES_DB: ${DB_NAME}
  #    POSTGRES_USER: ${DB_USERNAME}
  #    POSTGRES_PASSWORD: ${DB_PASSWORD}

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT_OUT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  #mariadb:
  #  image: mariadb:11.4.2-ubi
  #  container_name: mariadb
  #  restart: unless-stopped
  #  tty: true
  #  ports:
  #    - ${DB_PORT_OUT}:${DB_PORT}
  #  volumes:
  #    - db_data:/var/lib/mysql
  #    #- ./mariadb/init:/docker-entrypoint-initdb.d
  #  environment:
  #    MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #    MARIADB_DATABASE: ${DB_NAME}
  #    MARIADB_TEST_DB: ${DB_TEST}
  #    MARIADB_USER: ${DB_USERNAME}
  #    MARIADB_PASSWORD: ${DB_PASSWORD}
  #    SERVICE_TAGS: dev
  #    SERVICE_NAME: mariadb

  ruby-app:
    image: ruby-app:1.0.0
    container_name: ruby-app-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Use user id & group id in .env
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
      # Set the logins and groups identical to host environment
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_TEST: ${DB_TEST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      #- postgres
      - mysql
      #- mariadb

volumes:
  db_data:

networks:
  rails_network: